import type { SlotCategory } from "./types";

type Preset = {
  name: string;
  description: string;
};

export const PRESETS: Partial<Record<SlotCategory, Preset[]>> = {
  "mcp-server": [
    { name: "@modelcontextprotocol/server-filesystem", description: "ローカルファイルシステムへの安全なアクセス" },
    { name: "@modelcontextprotocol/server-github", description: "GitHub API連携（リポジトリ・Issue・PR管理）" },
    { name: "@modelcontextprotocol/server-postgres", description: "PostgreSQLデータベースへのクエリ実行" },
    { name: "@modelcontextprotocol/server-sqlite", description: "SQLiteデータベース操作・分析" },
    { name: "@modelcontextprotocol/server-brave-search", description: "Brave Search APIによるWeb検索" },
    { name: "@modelcontextprotocol/server-fetch", description: "URLからWebコンテンツを取得しMarkdownに変換" },
    { name: "@modelcontextprotocol/server-memory", description: "ナレッジグラフベースの永続メモリ" },
    { name: "@modelcontextprotocol/server-puppeteer", description: "Puppeteerによるブラウザ自動化" },
    { name: "@modelcontextprotocol/server-slack", description: "Slackワークスペース連携" },
    { name: "@modelcontextprotocol/server-gitlab", description: "GitLab API連携" },
    { name: "@modelcontextprotocol/server-google-maps", description: "Google Maps APIによる地図・検索" },
    { name: "@modelcontextprotocol/server-sequential-thinking", description: "動的な段階的思考プロセス支援" },
    { name: "@modelcontextprotocol/server-everart", description: "EverArt APIによるAI画像生成" },
    { name: "@executeautomation/playwright-mcp-server", description: "Playwrightによるブラウザテスト自動化" },
    { name: "@upstash/context7-mcp", description: "ライブラリの最新ドキュメント取得" },
    { name: "@21st-dev/magic-mcp", description: "UIコンポーネント検索・生成" },
    { name: "notion-mcp-server", description: "Notion API連携（ページ・DB操作）" },
    { name: "sentry-mcp-server", description: "Sentryエラートラッキング連携" },
    { name: "linear-mcp-server", description: "Linearプロジェクト管理連携" },
    { name: "supabase-mcp", description: "Supabase BaaS連携（DB・認証・ストレージ）" },
  ],
  plugin: [
    { name: "context7", description: "ライブラリドキュメントのリアルタイム検索" },
    { name: "code-review", description: "PRのコードレビュー自動化" },
    { name: "frontend-design", description: "高品質なフロントエンドUI生成" },
    { name: "eslint-integration", description: "ESLintによるコード品質チェック連携" },
    { name: "prettier-integration", description: "Prettierによるコード自動フォーマット" },
    { name: "test-runner", description: "テスト実行・結果分析" },
    { name: "docker-compose", description: "Docker Compose環境の管理・操作" },
    { name: "aws-toolkit", description: "AWSサービスの管理・デプロイ" },
    { name: "vercel-deploy", description: "Vercelへのデプロイ管理" },
    { name: "storybook", description: "Storybookコンポーネント管理" },
    { name: "figma-bridge", description: "Figmaデザインからコード変換" },
    { name: "openapi-generator", description: "OpenAPI仕様からコード自動生成" },
    { name: "i18n-manager", description: "国際化ファイルの管理・翻訳" },
    { name: "db-migration", description: "データベースマイグレーション管理" },
    { name: "performance-profiler", description: "パフォーマンス分析・最適化提案" },
    { name: "security-scanner", description: "セキュリティ脆弱性スキャン" },
    { name: "changelog-generator", description: "CHANGELOG自動生成" },
    { name: "dependency-checker", description: "依存関係の更新チェック・互換性確認" },
    { name: "graphql-toolkit", description: "GraphQLスキーマ管理・クエリ生成" },
    { name: "tailwind-helper", description: "Tailwind CSSクラスの補完・変換" },
  ],
  skill: [
    { name: "/commit", description: "変更を分析し適切なコミットメッセージを自動生成" },
    { name: "/review-pr", description: "Pull Requestのコードレビューを実施" },
    { name: "/frontend-design", description: "デザインモックからフロントエンド実装を生成" },
    { name: "/docs", description: "コードベースのドキュメントを自動生成" },
    { name: "/test", description: "ユニットテストを自動生成" },
    { name: "/refactor", description: "コードのリファクタリングを提案・実行" },
    { name: "/fix", description: "エラー・バグの根本原因を特定し修正" },
    { name: "/explain", description: "コードの仕組みやアーキテクチャを解説" },
    { name: "/migrate", description: "フレームワーク・ライブラリのバージョン移行支援" },
    { name: "/security-audit", description: "セキュリティ脆弱性のスキャン・修正提案" },
    { name: "/performance", description: "パフォーマンスボトルネックの分析・最適化" },
    { name: "/debug", description: "デバッグセッションの開始・問題特定支援" },
    { name: "/changelog", description: "git履歴からCHANGELOGエントリを自動生成" },
    { name: "/api-design", description: "REST/GraphQL APIの設計・実装支援" },
    { name: "/type-check", description: "TypeScript型安全性の強化・any除去" },
    { name: "/ci-cd", description: "CI/CDパイプライン設定ファイルの生成" },
    { name: "/convert", description: "コードを別言語・フレームワークに変換" },
    { name: "/i18n", description: "国際化対応（文字列抽出・翻訳ファイル生成）" },
    { name: "/db-schema", description: "DBスキーマ設計・マイグレーション生成" },
    { name: "/dependency-update", description: "依存パッケージの安全な更新手順を提案" },
  ],
};
