import type { SlotCategory } from "./types";

type Preset = {
  name: string;
  description: string;
};

export const CATEGORY_ORDER: SlotCategory[] = [
  "model",
  "mcp-server",
  "plugin",
  "skill",
  "claude-md",
  "hook",
  "custom",
];

export const PRESETS: Partial<Record<SlotCategory, Preset[]>> = {
  model: [
    { name: "Claude Opus 4.6", description: "最高性能モデル。複雑なタスクや高精度な出力に最適" },
    { name: "Claude Sonnet 4.5", description: "バランス型モデル。速度とコストと品質のバランスが良い" },
    { name: "Claude Haiku 4.5", description: "高速・低コストモデル。シンプルなタスクに最適" },
    { name: "Claude Sonnet 4", description: "前世代のバランス型モデル" },
    { name: "Claude Haiku 4", description: "前世代の高速モデル" },
  ],
  "mcp-server": [
    { name: "@modelcontextprotocol/server-filesystem", description: "ローカルファイルシステムへの安全なアクセス" },
    { name: "@modelcontextprotocol/server-github", description: "GitHub API連携（リポジトリ・Issue・PR管理）" },
    { name: "@modelcontextprotocol/server-postgres", description: "PostgreSQLデータベースへのクエリ実行" },
    { name: "@modelcontextprotocol/server-sqlite", description: "SQLiteデータベース操作・分析" },
    { name: "@modelcontextprotocol/server-brave-search", description: "Brave Search APIによるWeb検索" },
    { name: "@modelcontextprotocol/server-fetch", description: "URLからWebコンテンツを取得しMarkdownに変換" },
    { name: "@modelcontextprotocol/server-memory", description: "ナレッジグラフベースの永続メモリ" },
    { name: "@modelcontextprotocol/server-puppeteer", description: "Puppeteerによるブラウザ自動化" },
    { name: "@modelcontextprotocol/server-slack", description: "Slackワークスペース連携" },
    { name: "@modelcontextprotocol/server-gitlab", description: "GitLab API連携" },
    { name: "@modelcontextprotocol/server-google-maps", description: "Google Maps APIによる地図・検索" },
    { name: "@modelcontextprotocol/server-sequential-thinking", description: "動的な段階的思考プロセス支援" },
    { name: "@modelcontextprotocol/server-everart", description: "EverArt APIによるAI画像生成" },
    { name: "@executeautomation/playwright-mcp-server", description: "Playwrightによるブラウザテスト自動化" },
    { name: "@upstash/context7-mcp", description: "ライブラリの最新ドキュメント取得" },
    { name: "@21st-dev/magic-mcp", description: "UIコンポーネント検索・生成" },
    { name: "notion-mcp-server", description: "Notion API連携（ページ・DB操作）" },
    { name: "sentry-mcp-server", description: "Sentryエラートラッキング連携" },
    { name: "linear-mcp-server", description: "Linearプロジェクト管理連携" },
    { name: "supabase-mcp", description: "Supabase BaaS連携（DB・認証・ストレージ）" },
  ],
  plugin: [
    { name: "context7", description: "ライブラリドキュメントのリアルタイム検索" },
    { name: "code-review", description: "PRのコードレビュー自動化" },
    { name: "frontend-design", description: "高品質なフロントエンドUI生成" },
    { name: "eslint-integration", description: "ESLintによるコード品質チェック連携" },
    { name: "prettier-integration", description: "Prettierによるコード自動フォーマット" },
    { name: "test-runner", description: "テスト実行・結果分析" },
    { name: "docker-compose", description: "Docker Compose環境の管理・操作" },
    { name: "aws-toolkit", description: "AWSサービスの管理・デプロイ" },
    { name: "vercel-deploy", description: "Vercelへのデプロイ管理" },
    { name: "storybook", description: "Storybookコンポーネント管理" },
    { name: "figma-bridge", description: "Figmaデザインからコード変換" },
    { name: "openapi-generator", description: "OpenAPI仕様からコード自動生成" },
    { name: "i18n-manager", description: "国際化ファイルの管理・翻訳" },
    { name: "db-migration", description: "データベースマイグレーション管理" },
    { name: "performance-profiler", description: "パフォーマンス分析・最適化提案" },
    { name: "security-scanner", description: "セキュリティ脆弱性スキャン" },
    { name: "changelog-generator", description: "CHANGELOG自動生成" },
    { name: "dependency-checker", description: "依存関係の更新チェック・互換性確認" },
    { name: "graphql-toolkit", description: "GraphQLスキーマ管理・クエリ生成" },
    { name: "tailwind-helper", description: "Tailwind CSSクラスの補完・変換" },
  ],
  skill: [
    { name: "vercel-labs/skills:find-skills", description: "スキルの検索・発見を支援 (174.6K installs)" },
    { name: "vercel-labs/agent-skills:vercel-react-best-practices", description: "Vercel × React のベストプラクティス (114.9K installs)" },
    { name: "vercel-labs/agent-skills:web-design-guidelines", description: "Webデザインガイドライン (86.9K installs)" },
    { name: "remotion-dev/skills:remotion-best-practices", description: "Remotion動画生成のベストプラクティス (79.7K installs)" },
    { name: "anthropics/skills:frontend-design", description: "フロントエンドUI実装生成 (56.6K installs)" },
    { name: "vercel-labs/agent-skills:vercel-composition-patterns", description: "Vercelコンポジションパターン (32.2K installs)" },
    { name: "vercel-labs/agent-browser:agent-browser", description: "エージェントによるブラウザ操作 (28.5K installs)" },
    { name: "anthropics/skills:skill-creator", description: "カスタムスキルの作成支援 (28.2K installs)" },
    { name: "browser-use/browser-use:browser-use", description: "ブラウザ操作の自動化 (27.6K installs)" },
    { name: "vercel-labs/agent-skills:vercel-react-native-skills", description: "Vercel × React Native スキル (23.3K installs)" },
    { name: "nextlevelbuilder/ui-ux-pro-max-skill:ui-ux-pro-max", description: "プロレベルのUI/UXデザイン生成 (20.3K installs)" },
    { name: "squirrelscan/skills:audit-website", description: "Webサイトの監査・分析 (16.3K installs)" },
    { name: "coreyhaines31/marketingskills:seo-audit", description: "SEO監査・改善提案 (15.8K installs)" },
    { name: "obra/superpowers:brainstorming", description: "アイデアのブレインストーミング支援 (15.0K installs)" },
    { name: "supabase/agent-skills:supabase-postgres-best-practices", description: "Supabase × PostgreSQL ベストプラクティス (14.5K installs)" },
    { name: "anthropics/skills:pdf", description: "PDF ファイルの生成・操作 (12.0K installs)" },
    { name: "anthropics/skills:pptx", description: "PowerPoint ファイルの生成 (9.9K installs)" },
    { name: "better-auth/skills:better-auth-best-practices", description: "Better Auth 認証のベストプラクティス (9.5K installs)" },
    { name: "anthropics/skills:docx", description: "Word ドキュメントの生成 (9.3K installs)" },
    { name: "anthropics/skills:xlsx", description: "Excel スプレッドシートの生成 (9.2K installs)" },
  ],
};
